# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('number', models.CharField(help_text='Contract number', max_length=50)),
                ('description', models.TextField(help_text='Contract description')),
                ('start_date', models.DateField(help_text='Start date')),
                ('expiry_date', models.DateField(help_text='Expiry date')),
            ],
            options={
                'ordering': ['-expiry_date', 'start_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('serial', models.CharField(help_text='Serial No.', max_length=50)),
                ('manufacturer', models.CharField(help_text='Manufacturer', max_length=50)),
            ],
            options={
                'ordering': ['provider', 'name'],
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name', max_length=100)),
                ('rif', models.CharField(help_text='RIF', max_length=11)),
                ('address', models.TextField(help_text='Address')),
                ('phone_num', models.CharField(help_text='Phone number', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('legalentity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='procura.LegalEntity')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procura.Contract')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=('procura.legalentity',),
        ),
        migrations.AddField(
            model_name='item',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procura.Provider'),
        ),
    ]
