# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('procura', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='procura.Item')),
            ],
            options={
                'ordering': ['item'],
            },
        ),
    ]
