# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0002_auto_20171208_1510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contract',
            options={'ordering': ['expiry_date', 'start_date', 'name']},
        ),
    ]
