# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0004_auto_20171209_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Expiry date', null=True),
        ),
    ]
