# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 21:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_auto_20171209_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='expiry_date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Expiry date'),
            preserve_default=False,
        ),
    ]
